-- Database: inctrak_goals

-- DROP DATABASE inctrak_goals

-- dotnet ef dbcontext scaffold "Host=localhost;Database=inctrak_goals;Username=postgres;Password=" Npgsql.EntityFrameworkCore.PostgreSQL -o Models

CREATE DATABASE inctrak_goals;

\connect inctrak_goals
		
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TABLE LOGGED_ACTIONS (
	LOGGED_ACTIONS_PK bigserial primary key,
	GROUP_FK uuid NOT NULL,
	USER_FK uuid,
    USER_NAME text,
    TABLE_NAME text NOT NULL,
	TABLE_PK uuid NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    ACTION TEXT NOT NULL CHECK (ACTION IN ('I','U','U')),
    ORIGINAL_DATA hstore,
    NEW_DATA hstore
) WITH (fillfactor=100);
 
CREATE INDEX IDX_LOGGED_ACTIONS_TABLE_NAME ON lOGGED_ACTIONS(TABLE_NAME);
CREATE INDEX IDX_LOGGED_CREATED ON LOGGED_ACTIONS(CREATED);

CREATE OR REPLACE FUNCTION if_modified_func() RETURNS TRIGGER AS $body$
DECLARE
    audit_row LOGGED_ACTIONS;
    ORIGINAL_DATA hstore;
    NEW_DATA hstore;
	TABLE_PK uuid;
BEGIN
    IF TG_WHEN <> 'AFTER' THEN
        RAISE EXCEPTION 'if_modified_func() may only run as an AFTER trigger';
    END IF;

    IF (TG_OP = 'UPDATE' AND TG_LEVEL = 'ROW') THEN
        original_data = hstore(OLD.*);
        new_data =  (hstore(NEW.*) - original_data);
        IF new_data = hstore('') THEN
            -- All changed fields are ignored. Skip this update.
            RETURN NULL;
        END IF;
    ELSIF (TG_OP = 'DELETE' AND TG_LEVEL = 'ROW') THEN
        original_data = hstore(OLD.*);
    ELSIF (TG_OP = 'INSERT' AND TG_LEVEL = 'ROW') THEN
        original_data = hstore(NEW.*);
    ELSE
        RETURN NULL;
    END IF;

	select value::uuid into TABLE_PK from each(original_data) where key like '%_pk';

    INSERT INTO LOGGED_ACTIONS (GROUP_FK, USER_FK, USER_NAME, TABLE_NAME, TABLE_PK, ACTION, ORIGINAL_DATA, NEW_DATA)
	VALUES (current_setting('inctrak.group_key')::uuid, current_setting('inctrak.user_key')::uuid, current_setting('inctrak.user_name')::text, TG_TABLE_NAME::text, TABLE_PK, substring(TG_OP,1,1), original_data, new_data);
    RETURN NULL;
END;
$body$
LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION f_updated_column() 
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED = now();
    RETURN NEW; 
END;
$$ language 'plpgsql';

CREATE OR REPLACE FUNCTION f_groupkey_column() 
RETURNS TRIGGER AS $$
BEGIN
    NEW.GROUP_KEY = lower(regexp_replace(NEW.DESCRIPTION, '[^a-zA-Z0-9]+', '', 'g'));
    RETURN NEW; 
END;
$$ language 'plpgsql';

CREATE TABLE IMPORTANCE_TYPE (
	IMPORTANCE_TYPE_PK int NOT NULL PRIMARY KEY,
	NAME varchar(50) NOT NULL
);
CREATE UNIQUE INDEX UC_IMPORTANCE_TYPE_NAME ON IMPORTANCE_TYPE (lower(NAME));
INSERT INTO IMPORTANCE_TYPE (IMPORTANCE_TYPE_PK, NAME) VALUES (1, N'Lowest');
INSERT INTO IMPORTANCE_TYPE (IMPORTANCE_TYPE_PK, NAME) VALUES (2, N'Low');
INSERT INTO IMPORTANCE_TYPE (IMPORTANCE_TYPE_PK, NAME) VALUES (3, N'Medium');
INSERT INTO IMPORTANCE_TYPE (IMPORTANCE_TYPE_PK, NAME) VALUES (4, N'High');
INSERT INTO IMPORTANCE_TYPE (IMPORTANCE_TYPE_PK, NAME) VALUES (5, N'Highest');

CREATE TABLE RATING_TYPE(
	RATING_TYPE_PK int NOT NULL PRIMARY KEY,
	NAME varchar(50) NOT NULL
);
CREATE UNIQUE INDEX UC_RATING_TYPE_NAME ON RATING_TYPE (lower(NAME));
INSERT INTO RATING_TYPE (RATING_TYPE_PK, NAME) VALUES (1, N'Far Below Expectations');
INSERT INTO RATING_TYPE (RATING_TYPE_PK, NAME) VALUES (2, N'Below Expectations');
INSERT INTO RATING_TYPE (RATING_TYPE_PK, NAME) VALUES (3, N'Meets Expeciations');
INSERT INTO RATING_TYPE (RATING_TYPE_PK, NAME) VALUES (4, N'Exceeded Expeciations');
INSERT INTO RATING_TYPE (RATING_TYPE_PK, NAME) VALUES (5, N'Far Exceeded Expeciations');


CREATE TABLE GROUPS(
	GROUP_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	DESCRIPTION varchar(256) NOT NULL,
	GROUP_KEY varchar(256) NOT NULL,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_GROUP_DESC ON GROUPS (lower(DESCRIPTION));
CREATE UNIQUE INDEX UC_GROUP_KEY ON GROUPS (GROUP_KEY);
CREATE TRIGGER group_key_groups BEFORE UPDATE ON GROUPS FOR EACH ROW EXECUTE PROCEDURE  f_groupkey_column();
CREATE TRIGGER updated_groups BEFORE UPDATE ON GROUPS FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();

CREATE TABLE USERS(
	USER_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	GROUP_FK uuid NOT NULL REFERENCES GROUPS,
	USER_NAME varchar(256) NOT NULL,
	EMAIL_ADDRESS varchar(256) NOT NULL,
	ACTIVATED bool NOT NULL,
	PASSWORD varchar(512) NOT NULL,
	ADMINISTRATOR bool NOT NULL,
	ACCEPT_TERMS bool NOT NULL,
	GOOGLE_LOGON bool NOT NULL,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_EMAIL ON USERS (lower(EMAIL_ADDRESS));
CREATE UNIQUE INDEX UC_USER ON USERS (lower(USER_NAME));
CREATE TRIGGER updated_users BEFORE UPDATE ON USERS FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();

CREATE TABLE ACTIVATE_UUIDS(
	UUID_PK serial NOT NULL PRIMARY KEY,
	USER_FK uuid NOT NULL REFERENCES USERS ON DELETE CASCADE,
	UUID varchar(32) NOT NULL UNIQUE,
	"TYPE" int NOT NULL,
	VALID_UNTIL timestamp with time zone NOT NULL,
	UNIQUE("TYPE", USER_FK)
);

CREATE TABLE DEPARTMENTS (
	DEPARTMENT_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	GROUP_FK uuid NOT NULL REFERENCES GROUPS,
	NAME varchar(256) NOT NULL,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_DEPARTMENT_NAME ON DEPARTMENTS (GROUP_FK, lower(NAME));
CREATE TRIGGER updated_departments BEFORE UPDATE ON DEPARTMENTS FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();
CREATE TRIGGER t_change_department
	AFTER INSERT OR UPDATE OR DELETE ON DEPARTMENTS
	FOR EACH ROW EXECUTE PROCEDURE if_modified_func();

CREATE TABLE MEMBERS (
	MEMBER_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	GROUP_FK uuid NOT NULL REFERENCES GROUPS,
	USER_FK uuid NULL REFERENCES USERS,
	NAME varchar(256) NOT NULL,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TRIGGER updated_members BEFORE UPDATE ON MEMBERS FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();
CREATE TRIGGER t_change_member
	AFTER INSERT OR UPDATE OR DELETE ON MEMBERS
	FOR EACH ROW EXECUTE PROCEDURE if_modified_func();


CREATE TABLE TEAMS (
	TEAM_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	GROUP_FK uuid NOT NULL REFERENCES GROUPS,
	DEPARTMENT_FK uuid NOT NULL REFERENCES DEPARTMENTS,
	NAME varchar(256) NOT NULL,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_TEAM_NAME ON TEAMS (GROUP_FK, lower(NAME));
CREATE TRIGGER updated_teams BEFORE UPDATE ON TEAMS FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();
CREATE TRIGGER t_change_team
	AFTER INSERT OR UPDATE OR DELETE ON TEAMS
	FOR EACH ROW EXECUTE PROCEDURE if_modified_func();

CREATE TABLE SCHEDULES(
	SCHEDULE_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	GROUP_FK uuid NOT NULL REFERENCES GROUPS,
	NAME varchar(256) NOT NULL,
	START_DATE date NOT NULL,
	END_DATE date NOT NULL,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_SCHEDULE_NAME ON SCHEDULES (GROUP_FK, lower(NAME));
CREATE TRIGGER updated_schedules BEFORE UPDATE ON SCHEDULES FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();
CREATE TRIGGER t_change_schedule
	AFTER INSERT OR UPDATE OR DELETE ON SCHEDULES
	FOR EACH ROW EXECUTE PROCEDURE if_modified_func();

CREATE TABLE GOALSET (
	GOALSET_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	GROUP_FK uuid NOT NULL REFERENCES GROUPS,
	MEMBER_FK uuid NOT NULL REFERENCES MEMBERS,
	TEAM_FK uuid NOT NULL REFERENCES TEAMS,
	SCHEDULE_FK uuid NOT NULL REFERENCES SCHEDULES,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_GOALSET_MEMBER_SCHED ON GOALSET (MEMBER_FK, SCHEDULE_FK);
CREATE TRIGGER updated_goalset BEFORE UPDATE ON GOALSET FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();
CREATE TRIGGER t_change_goalset
	AFTER INSERT OR UPDATE OR DELETE ON GOALSET
	FOR EACH ROW EXECUTE PROCEDURE if_modified_func();

CREATE TABLE GOALS (
	GOALS_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
	GROUP_FK uuid NOT NULL REFERENCES GROUPS,
	GOALSET_FK uuid NOT NULL REFERENCES GOALSET,
	IMPORTANCE_TYPE_FK int NOT NULL REFERENCES IMPORTANCE_TYPE,
	DESCRIPTION text NOT NULL,
	RATING_TYPE_FK int REFERENCES RATING_TYPE,
	MANAGER_COMMENTS text,
	MEMBER_COMMENTS text,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_GOALS_SET_DESC ON GOALS (GOALSET_FK, lower(DESCRIPTION));
CREATE TRIGGER updated_goals BEFORE UPDATE ON GOALS FOR EACH ROW EXECUTE PROCEDURE  f_updated_column();
CREATE TRIGGER t_change_goal
	AFTER INSERT OR UPDATE OR DELETE ON GOALS
	FOR EACH ROW EXECUTE PROCEDURE if_modified_func();
