-- Database: inctrak_feedback

-- DROP DATABASE inctrak_feedback;

-- dotnet ef dbcontext scaffold "Host=localhost;Database=inctrak_feedback;Username=postgres;Password=" Npgsql.EntityFrameworkCore.PostgreSQL -o FeedbackModels

CREATE DATABASE inctrak_feedback;

\connect inctrak_feedback;

CREATE TABLE MESSAGE_TYPE (
	MESSAGE_TYPE_PK int NOT NULL PRIMARY KEY ,
	MESSAGE_TYPE varchar(30) NOT NULL
);

INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (1, 'Suggestion');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (2, 'Comment');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (3, 'Issue Found');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (4, 'Question');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (5, 'Complaint');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (6, 'Other');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (7, 'Compliment');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (8, 'Contact Us');
INSERT INTO MESSAGE_TYPE (MESSAGE_TYPE_PK, MESSAGE_TYPE) VALUES (9, 'Quick Vesting');

CREATE TABLE FEEDBACK (
	FEEDBACK_PK serial NOT NULL PRIMARY KEY,
	MESSAGE_TYPE_FK int NOT NULL REFERENCES MESSAGE_TYPE,
	CREATED timestamp with time zone NOT NULL DEFAULT now(),
	EMAIL_ADDRESS varchar(128) NOT NULL,
	NAME varchar(50) NOT NULL,
	SUBJECT varchar(50) NOT NULL,
	MESSAGE text NOT NULL,
	CLIENT_DATA text NULL
);
