-- Bootstrap schema for the inctrak_template tenant database.
-- Apply this to an empty PostgreSQL database, then mark that database as
-- TEMPLATE so new tenant databases can be cloned from it.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE OR REPLACE FUNCTION f_updated_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPDATED = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE FUNCTION f_groupkey_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.GROUP_KEY = lower(regexp_replace(NEW.DESCRIPTION, '[^a-zA-Z0-9]+', '', 'g'));
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TABLE SCHEMA_VERSION(
    SCHEMA_VERSION_PK int NOT NULL PRIMARY KEY,
    VERSION_NAME varchar(100) NOT NULL UNIQUE,
    APPLIED timestamp with time zone NOT NULL DEFAULT now()
);

INSERT INTO SCHEMA_VERSION (SCHEMA_VERSION_PK, VERSION_NAME)
VALUES (1, 'template-bootstrap-v1');

CREATE TABLE AMOUNT_TYPES(
    AMOUNT_TYPE_PK int NOT NULL PRIMARY KEY,
    NAME varchar(50) NOT NULL
);
CREATE UNIQUE INDEX UC_NAME ON AMOUNT_TYPES (lower(NAME));
INSERT INTO AMOUNT_TYPES (AMOUNT_TYPE_PK, NAME) VALUES (1, 'Shares');
INSERT INTO AMOUNT_TYPES (AMOUNT_TYPE_PK, NAME) VALUES (2, 'Percentage');

CREATE TABLE PARTICIPANT_TYPES(
    PARTICIPANT_TYPE_PK int NOT NULL PRIMARY KEY,
    NAME varchar(50) NOT NULL
);
CREATE UNIQUE INDEX UC_PARTICIPANT_TYPE_NAME ON PARTICIPANT_TYPES (lower(NAME));
INSERT INTO PARTICIPANT_TYPES (PARTICIPANT_TYPE_PK, NAME) VALUES (1, 'Founder');
INSERT INTO PARTICIPANT_TYPES (PARTICIPANT_TYPE_PK, NAME) VALUES (2, 'Investor');
INSERT INTO PARTICIPANT_TYPES (PARTICIPANT_TYPE_PK, NAME) VALUES (4, 'Consultant');
INSERT INTO PARTICIPANT_TYPES (PARTICIPANT_TYPE_PK, NAME) VALUES (3, 'Employee');

CREATE TABLE PERIOD_TYPES(
    PERIOD_TYPE_PK int NOT NULL PRIMARY KEY,
    NAME varchar(50) NOT NULL
);
CREATE UNIQUE INDEX UC_PERIOD_TYPE_NAME ON PERIOD_TYPES (lower(NAME));
INSERT INTO PERIOD_TYPES (PERIOD_TYPE_PK, NAME) VALUES (1, 'Years');
INSERT INTO PERIOD_TYPES (PERIOD_TYPE_PK, NAME) VALUES (2, 'Months');
INSERT INTO PERIOD_TYPES (PERIOD_TYPE_PK, NAME) VALUES (3, 'Weeks');
INSERT INTO PERIOD_TYPES (PERIOD_TYPE_PK, NAME) VALUES (4, 'Days');

CREATE TABLE TERM_FROMS(
    TERM_FROM_PK int NOT NULL PRIMARY KEY,
    NAME varchar(50) NOT NULL
);
CREATE UNIQUE INDEX UC_TERM_FROM_NAME ON TERM_FROMS (lower(NAME));
INSERT INTO TERM_FROMS (TERM_FROM_PK, NAME) VALUES (-1, 'Absolute Date Chosen');
INSERT INTO TERM_FROMS (TERM_FROM_PK, NAME) VALUES (1, 'Grant Date');
INSERT INTO TERM_FROMS (TERM_FROM_PK, NAME) VALUES (2, 'Vest Start Date');
INSERT INTO TERM_FROMS (TERM_FROM_PK, NAME) VALUES (3, 'Specific Date');

CREATE TABLE GROUPS(
    GROUP_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    DESCRIPTION varchar(256) NOT NULL,
    GROUP_KEY varchar(256) NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_GROUP_DESC ON GROUPS (lower(DESCRIPTION));
CREATE UNIQUE INDEX UC_GROUP_KEY ON GROUPS (GROUP_KEY);
CREATE TRIGGER group_key_groups BEFORE UPDATE ON GROUPS FOR EACH ROW EXECUTE PROCEDURE f_groupkey_column();
CREATE TRIGGER updated_groups BEFORE UPDATE ON GROUPS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE USERS(
    USER_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    USER_NAME varchar(256) NOT NULL,
    EMAIL_ADDRESS varchar(256) NOT NULL,
    ACTIVATED bool NOT NULL,
    PASSWORD varchar(512) NOT NULL,
    ADMINISTRATOR bool NOT NULL,
    ACCEPT_TERMS bool NOT NULL,
    GOOGLE_LOGON bool NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_EMAIL ON USERS (lower(EMAIL_ADDRESS));
CREATE UNIQUE INDEX UC_USER ON USERS (lower(USER_NAME));
CREATE TRIGGER updated_users BEFORE UPDATE ON USERS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE ACTIVATE_UUIDS(
    UUID_PK serial NOT NULL PRIMARY KEY,
    USER_FK uuid NOT NULL REFERENCES USERS ON DELETE CASCADE,
    UUID varchar(32) NOT NULL UNIQUE,
    "TYPE" int NOT NULL,
    VALID_UNTIL timestamp with time zone NOT NULL,
    UNIQUE("TYPE", USER_FK)
);

CREATE TABLE STOCK_CLASSES(
    STOCK_CLASS_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    NAME varchar(256) NOT NULL,
    TOTAL_SHARES decimal(18, 0) NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_STOCK_CLASS_NAME ON STOCK_CLASSES (GROUP_FK, lower(NAME));
CREATE TRIGGER updated_stock_classes BEFORE UPDATE ON STOCK_CLASSES FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE PARTICIPANTS(
    PARTICIPANT_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    USER_FK uuid NULL REFERENCES USERS,
    PARTICIPANT_TYPE_FK int NOT NULL REFERENCES PARTICIPANT_TYPES,
    NAME varchar(256) NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TRIGGER updated_participants BEFORE UPDATE ON PARTICIPANTS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE STOCK_HOLDERS(
    STOCK_HOLDER_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    PARTICIPANT_FK uuid NOT NULL REFERENCES PARTICIPANTS,
    STOCK_CLASS_FK uuid NOT NULL REFERENCES STOCK_CLASSES,
    SHARES decimal(18, 0) NOT NULL,
    PRICE decimal(18, 6) NOT NULL,
    DATE_OF_SALE date NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TRIGGER updated_stock_holders BEFORE UPDATE ON STOCK_HOLDERS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE PLANS(
    PLAN_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    STOCK_CLASS_FK uuid NOT NULL REFERENCES STOCK_CLASSES,
    NAME varchar(256) NOT NULL,
    TOTAL_SHARES decimal(18, 0) NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_PLAN_NAME ON PLANS (GROUP_FK, lower(NAME));
CREATE TRIGGER updated_plans BEFORE UPDATE ON PLANS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE SCHEDULES(
    SCHEDULE_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    NAME varchar(256) NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_SCHEDULE_NAME ON SCHEDULES (GROUP_FK, lower(NAME));
CREATE TRIGGER updated_schedules BEFORE UPDATE ON SCHEDULES FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE TERMINATIONS(
    TERMINATION_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    TERM_FROM_FK int NOT NULL REFERENCES TERM_FROMS,
    NAME varchar(256) NOT NULL,
    ABSOLUTE_DATE date NOT NULL,
    YEARS int NOT NULL,
    MONTHS int NOT NULL,
    DAYS int NOT NULL,
    SPECIFIC_DATE date NOT NULL,
    IS_ABSOLUTE bool NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX UC_TERMINATION_NAME ON TERMINATIONS (GROUP_FK, lower(NAME));
CREATE TRIGGER updated_terminations BEFORE UPDATE ON TERMINATIONS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE GRANTS(
    GRANT_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    PARTICIPANT_FK uuid NOT NULL REFERENCES PARTICIPANTS,
    PLAN_FK uuid NOT NULL REFERENCES PLANS,
    VESTING_SCHEDULE_FK uuid NOT NULL REFERENCES SCHEDULES,
    TERMINATION_FK uuid NOT NULL REFERENCES TERMINATIONS,
    SHARES decimal(18, 0) NOT NULL,
    OPTION_PRICE decimal(18, 6) NOT NULL,
    VESTING_START date NOT NULL,
    DATE_OF_GRANT date NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TRIGGER updated_grants BEFORE UPDATE ON GRANTS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();

CREATE TABLE PERIODS(
    PERIOD_PK uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
    GROUP_FK uuid NOT NULL REFERENCES GROUPS,
    SCHEDULE_FK uuid NOT NULL REFERENCES SCHEDULES ON DELETE CASCADE,
    PERIOD_TYPE_FK int NOT NULL REFERENCES PERIOD_TYPES,
    AMOUNT_TYPE_FK int NOT NULL REFERENCES AMOUNT_TYPES,
    AMOUNT decimal(18, 6) NOT NULL,
    "ORDER" int NOT NULL,
    EVEN_OVER_N int NOT NULL,
    INCREMENTS int NOT NULL,
    PERIOD_AMOUNT int NOT NULL,
    CREATED timestamp with time zone NOT NULL DEFAULT now(),
    UPDATED timestamp with time zone NOT NULL DEFAULT now()
);
CREATE TRIGGER updated_periods BEFORE UPDATE ON PERIODS FOR EACH ROW EXECUTE PROCEDURE f_updated_column();
