version: "3"

services:
  db_node_inctrak_goals:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dbinit/inctrak_errors.sql:/docker-entrypoint-initdb.d/1-inctrak_errors.sql
      - ./dbinit/inctrak_feedback.sql:/docker-entrypoint-initdb.d/1-inctrak_feedback.sql
      - ./dbinit/inctrak_goals.sql:/docker-entrypoint-initdb.d/2-inctrak_goals.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "inctrak_goals_db"
    restart: always
    container_name: inctrak_goals_db

  inctrak_goals:
    image: inctrak_goals:latest
    depends_on:
      - db_node_inctrak_goals
    expose:
      - 80
    restart: always
    volumes:
      - ./app/appsettings.json:/app/appsettings.json
    environment:
      VIRTUAL_HOST: goals.inctrak.com
      LETSENCRYPT_HOST: goals.inctrak.com
      LETSENCRYPT_EMAIL: calypsosystemsllc@gmail.com
    container_name: inctrak_goals
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy

